// AI 생성 프롬프트(generate-quiz)의 DIFFICULTY_GUIDES를 구조화한 것.
// 이 파일이 유일한 문법 기준이다 — 항목 추가·급수 변경은 여기서만 한다.
// GRAMMAR_ITEMS와 LEVEL_TEMPLATE로부터 renderGuide()가 기존 DIFFICULTY_GUIDES 문자열을
// 한 글자도 틀리지 않게 재생성한다(검증: scratchpad/extract-grammar.mjs로 byte-exact 비교).

export type CefrLevel = "A1" | "A2" | "B1" | "B2" | "C1" | "C2";

export type GrammarItem = {
  id: string;
  form: string;
  level: CefrLevel;
  category: string;
};

// 문장 은행 등에서 참고할 급수별 목표 문장 길이. DIFFICULTY_GUIDES의 "길이:" 줄과 같은 값이다.
//
// 단위는 "단어"가 아니라 "어절"이다 — measure-baseline.ts가 공백 분할(split(/\s+/))로 세고
// 있었고, 실측 결과(A1 5.1 ± 1.2 등)가 기존 숫자와 맞아떨어져 라벨만 잘못돼 있었음을 확인했다.
// A2/B1/B2는 실측 SD(1.5 → 1.8 → 2.6)에 맞춰 범위 폭도 3 → 4 → 5로 넓혔다(SD가 클수록
// 실제 편차가 크므로 범위를 좁게 잡으면 정상 문장도 자주 벗어난다). A1/C1/C2는 실측이
// 범위 안이었거나(A1) 아직 측정하지 않아(C1/C2) 숫자는 그대로 두고 라벨만 고쳤다.
export const LEVEL_SENTENCE_LENGTH: Record<CefrLevel, string> = {
  A1: "5-8어절(띄어쓰기로 나눈 덩어리 수)",
  A2: "7-10어절(띄어쓰기로 나눈 덩어리 수)",
  B1: "9-13어절(띄어쓰기로 나눈 덩어리 수)",
  B2: "12-17어절(띄어쓰기로 나눈 덩어리 수)",
  C1: "16-24어절(띄어쓰기로 나눈 덩어리 수)",
  C2: "16-28어절(띄어쓰기로 나눈 덩어리 수)",
};

export const GRAMMAR_ITEMS: GrammarItem[] = [
  { id: "a1-1-1", form: "-이에요/예요", level: "A1", category: "서술/종결" },
  { id: "a1-1-2", form: "-아/어요", level: "A1", category: "서술/종결" },
  { id: "a1-1-3", form: "-았/었어요(과거)", level: "A1", category: "서술/종결" },
  { id: "a1-1-4", form: "-지요?(확인)", level: "A1", category: "서술/종결" },
  { id: "a1-2-1", form: "이거/그거/저거", level: "A1", category: "지시/장소" },
  { id: "a1-2-2", form: "여기/거기/저기", level: "A1", category: "지시/장소" },
  { id: "a1-3-1", form: "은/는(주제)", level: "A1", category: "조사" },
  { id: "a1-3-2", form: "이/가(주어/아니다)", level: "A1", category: "조사" },
  { id: "a1-3-3", form: "을/를(목적)", level: "A1", category: "조사" },
  { id: "a1-3-4", form: "도(포함)", level: "A1", category: "조사" },
  { id: "a1-3-5", form: "에(위치/시간)", level: "A1", category: "조사" },
  { id: "a1-3-6", form: "에서(장소/출발)", level: "A1", category: "조사" },
  { id: "a1-3-7", form: "부터&까지", level: "A1", category: "조사" },
  { id: "a1-3-8", form: "(으)로(방향/수단)", level: "A1", category: "조사" },
  { id: "a1-3-9", form: "하고&와/과(나열)", level: "A1", category: "조사" },
  { id: "a1-3-10", form: "만(한정)", level: "A1", category: "조사" },
  { id: "a1-3-11", form: "한테&께(대상)", level: "A1", category: "조사" },
  { id: "a1-3-12", form: "의(소유)", level: "A1", category: "조사" },
  { id: "a1-3-13", form: "위&아래&앞&뒤", level: "A1", category: "조사" },
  { id: "a1-4-1", form: "안(부정)", level: "A1", category: "부정" },
  { id: "a1-4-2", form: "못(불가능)", level: "A1", category: "부정" },
  { id: "a1-4-3", form: "이/가 아니다", level: "A1", category: "부정" },
  { id: "a1-5-1", form: "있어요/없어요", level: "A1", category: "존재" },
  { id: "a1-6-1", form: "-고 싶다", level: "A1", category: "희망" },
  { id: "a1-6-2", form: "-고 싶어 하다", level: "A1", category: "희망" },
  { id: "a1-7-1", form: "-(으)ㄹ 거예요(미래)", level: "A1", category: "계획/미래" },
  { id: "a1-7-2", form: "-(으)려고 해요", level: "A1", category: "계획/미래" },
  { id: "a1-8-1", form: "-(으)러 가다/오다", level: "A1", category: "목적" },
  { id: "a1-9-1", form: "-(으)ㄹ 수 있다/없다", level: "A1", category: "능력/숙련도" },
  { id: "a1-9-2", form: "못하다/잘하다/잘 못하다", level: "A1", category: "능력/숙련도" },
  { id: "a1-10-1", form: "-아야/어야 해요", level: "A1", category: "의무" },
  { id: "a1-10-2", form: "-아야/어야 되다", level: "A1", category: "의무" },
  { id: "a1-11-1", form: "-아서/어서(이유)", level: "A1", category: "이유" },
  { id: "a1-12-1", form: "-(으)면", level: "A1", category: "조건" },
  { id: "a1-13-1", form: "-지만", level: "A1", category: "대조/나열" },
  { id: "a1-13-2", form: "근데", level: "A1", category: "대조/나열" },
  { id: "a1-13-3", form: "-고(동작 나열)", level: "A1", category: "대조/나열" },
  { id: "a1-14-1", form: "-(으)ㄹ 때", level: "A1", category: "시간" },
  { id: "a1-15-1", form: "-고 있다", level: "A1", category: "진행" },
  { id: "a1-16-1", form: "-(으)시다", level: "A1", category: "높임" },
  { id: "a1-16-2", form: "-(이)세요", level: "A1", category: "높임" },
  { id: "a1-17-1", form: "-(으)세요", level: "A1", category: "요청/권유" },
  { id: "a1-17-2", form: "-지 마세요", level: "A1", category: "요청/권유" },
  { id: "a1-17-3", form: "-(으)ㄹ까요?(권유)", level: "A1", category: "요청/권유" },
  { id: "a1-17-4", form: "N 주세요", level: "A1", category: "요청/권유" },
  { id: "a1-18-1", form: "-아/어 주다", level: "A1", category: "도움" },
  { id: "a1-18-2", form: "-아/어 드릴까요?", level: "A1", category: "도움" },
  { id: "a1-18-3", form: "-아/어 드릴게요", level: "A1", category: "도움" },
  { id: "a1-18-4", form: "-아/어 주시겠어요?", level: "A1", category: "도움" },
  { id: "a1-19-1", form: "-아/어 보세요", level: "A1", category: "시도/권유" },
  { id: "a1-20-1", form: "형용사+-(으)ㄴ", level: "A1", category: "수식" },
  { id: "a1-21-1", form: "개/병/잔/그릇", level: "A1", category: "단위" },
  { id: "a2-1-1", form: "-네요(감탄)", level: "A2", category: "서술/종결" },
  { id: "a2-1-2", form: "-다/-ㄴ다/-는다(문어체)", level: "A2", category: "서술/종결" },
  { id: "a2-1-3", form: "N(이)다(문어체)", level: "A2", category: "서술/종결" },
  { id: "a2-2-1", form: "-(으)ㄴ가요?", level: "A2", category: "의문(부드러움)" },
  { id: "a2-2-2", form: "-나요?", level: "A2", category: "의문(부드러움)" },
  { id: "a2-2-3", form: "N인가요?", level: "A2", category: "의문(부드러움)" },
  { id: "a2-3-1", form: "-지 않다(장형 부정)", level: "A2", category: "부정" },
  { id: "a2-4-1", form: "-(으)니까", level: "A2", category: "이유(심화)" },
  { id: "a2-4-2", form: "-기 때문에", level: "A2", category: "이유(심화)" },
  { id: "a2-4-3", form: "N 때문에", level: "A2", category: "이유(심화)" },
  { id: "a2-4-4", form: "N(이)라서", level: "A2", category: "이유(심화)" },
  { id: "a2-5-1", form: "-아서/어서(순서)", level: "A2", category: "순서(연속 동작)" },
  { id: "a2-5-2", form: "-고 나서", level: "A2", category: "순서(연속 동작)" },
  { id: "a2-6-1", form: "-(으)면서", level: "A2", category: "동시동작/시간" },
  { id: "a2-6-2", form: "-는 동안에", level: "A2", category: "동시동작/시간" },
  { id: "a2-6-3", form: "N 동안", level: "A2", category: "동시동작/시간" },
  { id: "a2-6-4", form: "-다가(전환)", level: "A2", category: "동시동작/시간" },
  { id: "a2-6-5", form: "-(으)ㄴ 지(경과)", level: "A2", category: "동시동작/시간" },
  { id: "a2-6-6", form: "-기 전에", level: "A2", category: "동시동작/시간" },
  { id: "a2-6-7", form: "-(으)ㄴ 후에", level: "A2", category: "동시동작/시간" },
  { id: "a2-6-8", form: "-았/었을 때", level: "A2", category: "동시동작/시간" },
  { id: "a2-7-1", form: "-는데/-(으)ㄴ데(연결)", level: "A2", category: "배경/대조" },
  { id: "a2-7-2", form: "-(으)ㄴ데요", level: "A2", category: "배경/대조" },
  { id: "a2-7-3", form: "-는데요", level: "A2", category: "배경/대조" },
  { id: "a2-7-4", form: "N인데요", level: "A2", category: "배경/대조" },
  { id: "a2-7-5", form: "형용사+-(으)ㄴ데", level: "A2", category: "배경/대조" },
  { id: "a2-8-1", form: "-(으)ㄹ까요?(추측)", level: "A2", category: "추측" },
  { id: "a2-8-2", form: "-(으)ㄹ 거예요(추측)", level: "A2", category: "추측" },
  { id: "a2-8-3", form: "-(으)ㄹ 것 같다", level: "A2", category: "추측" },
  { id: "a2-8-4", form: "-(으)ㄴ/는 것 같다", level: "A2", category: "추측" },
  { id: "a2-8-5", form: "N인 것 같다", level: "A2", category: "추측" },
  { id: "a2-9-1", form: "-아/어 보이다", level: "A2", category: "양태/외견" },
  { id: "a2-9-2", form: "-(으)ㄹ지 모르겠다", level: "A2", category: "양태/외견" },
  { id: "a2-10-1", form: "-(으)ㅂ시다", level: "A2", category: "제안/의지/권유" },
  { id: "a2-10-2", form: "-(으)ㄹ래요", level: "A2", category: "제안/의지/권유" },
  { id: "a2-10-3", form: "-(으)ㄹ게요", level: "A2", category: "제안/의지/권유" },
  { id: "a2-10-4", form: "-겠어요", level: "A2", category: "제안/의지/권유" },
  { id: "a2-10-5", form: "-는 게 좋겠다", level: "A2", category: "제안/의지/권유" },
  { id: "a2-10-6", form: "-는 게 어때요?", level: "A2", category: "제안/의지/권유" },
  { id: "a2-11-1", form: "-(으)려고", level: "A2", category: "계획/의도" },
  { id: "a2-12-1", form: "-기로 하다", level: "A2", category: "결심/약속/계획" },
  { id: "a2-12-2", form: "-(으)ㄹ까 하다", level: "A2", category: "결심/약속/계획" },
  { id: "a2-13-1", form: "-았/었으면 좋겠다", level: "A2", category: "희망" },
  { id: "a2-14-1", form: "-아도/어도 되다", level: "A2", category: "허락/금지" },
  { id: "a2-14-2", form: "-(으)면 안 되다", level: "A2", category: "허락/금지" },
  { id: "a2-15-1", form: "-아도/어도", level: "A2", category: "양보" },
  { id: "a2-15-2", form: "-기는 하지만", level: "A2", category: "양보" },
  { id: "a2-16-1", form: "-게 되다", level: "A2", category: "변화" },
  { id: "a2-16-2", form: "-아/어지다", level: "A2", category: "변화" },
  { id: "a2-17-1", form: "-(으)ㄴ 적이 있다/없다", level: "A2", category: "경험/시도" },
  { id: "a2-17-2", form: "-아/어 보다", level: "A2", category: "경험/시도" },
  { id: "a2-17-3", form: "-(으)ㄹ 뻔하다", level: "A2", category: "경험/시도" },
  { id: "a2-18-1", form: "-(으)ㄹ 줄 알다/모르다", level: "A2", category: "능력/숙련도" },
  { id: "a2-19-1", form: "-기(가) 쉽다/어렵다", level: "A2", category: "평가" },
  { id: "a2-20-1", form: "-(으)려면", level: "A2", category: "조건/방법" },
  { id: "a2-20-2", form: "-(으)면 되다", level: "A2", category: "조건/방법" },
  { id: "a2-20-3", form: "-(으)ㄹ 테니까", level: "A2", category: "조건/방법" },
  { id: "a2-21-1", form: "-는 중이다", level: "A2", category: "상태/성향" },
  { id: "a2-21-2", form: "N 중이다", level: "A2", category: "상태/성향" },
  { id: "a2-21-3", form: "-(으)ㄴ/는 편이다", level: "A2", category: "상태/성향" },
  { id: "a2-22-1", form: "-아/어 있다(상태 지속)", level: "A2", category: "보조용언" },
  { id: "a2-22-2", form: "-아/어 놓다", level: "A2", category: "보조용언" },
  { id: "a2-22-3", form: "-아/어 버리다", level: "A2", category: "보조용언" },
  { id: "a2-22-4", form: "-아/어다 주다", level: "A2", category: "보조용언" },
  { id: "a2-23-1", form: "-거나", level: "A2", category: "나열/선택" },
  { id: "a2-23-2", form: "(이)나(명사 나열)", level: "A2", category: "나열/선택" },
  { id: "a2-24-1", form: "밖에", level: "A2", category: "조사" },
  { id: "a2-24-2", form: "마다", level: "A2", category: "조사" },
  { id: "a2-24-3", form: "처럼&같이", level: "A2", category: "조사" },
  { id: "a2-24-4", form: "중에(서)", level: "A2", category: "조사" },
  { id: "a2-24-5", form: "N 대신", level: "A2", category: "조사" },
  { id: "a2-25-1", form: "보다 더", level: "A2", category: "비교" },
  { id: "a2-26-1", form: "형용사+-게", level: "A2", category: "부사형" },
  { id: "a2-27-1", form: "N(이)라고 하다", level: "A2", category: "인용(명사)" },
  { id: "a2-28-1", form: "-는 것", level: "A2", category: "명사화" },
  { id: "a2-29-1", form: "(동사)+-는", level: "A2", category: "관형사형" },
  { id: "a2-29-2", form: "(동사)+-(으)ㄴ", level: "A2", category: "관형사형" },
  { id: "a2-29-3", form: "(동사)+-(으)ㄹ", level: "A2", category: "관형사형" },
  { id: "a2-30-1", form: "-(으)ㄴ/는지 알다", level: "A2", category: "지식/인지" },
  { id: "a2-30-2", form: "N인지 알다/모르다", level: "A2", category: "지식/인지" },
  { id: "b1-1-1", form: "-느라고", level: "B1", category: "연결어미" },
  { id: "b1-1-2", form: "-는 대신에", level: "B1", category: "연결어미" },
  { id: "b1-1-3", form: "-다가", level: "B1", category: "연결어미" },
  { id: "b1-1-4", form: "-더니", level: "B1", category: "연결어미" },
  { id: "b1-1-5", form: "-던", level: "B1", category: "연결어미" },
  { id: "b1-2-1", form: "-다고 하다", level: "B1", category: "간접화법" },
  { id: "b1-2-2", form: "-ㄴ/는다고 하다", level: "B1", category: "간접화법" },
  { id: "b1-2-3", form: "-았/었다고 하다", level: "B1", category: "간접화법" },
  { id: "b1-2-4", form: "-(으)ㄹ 거라고 하다", level: "B1", category: "간접화법" },
  { id: "b1-2-5", form: "-자고 하다", level: "B1", category: "간접화법" },
  { id: "b1-2-6", form: "-냐고 하다", level: "B1", category: "간접화법" },
  { id: "b1-2-7", form: "-(으)라고 하다", level: "B1", category: "간접화법" },
  { id: "b1-3-1", form: "-(으)ㄴ/는 것 같다", level: "B1", category: "추측/판단" },
  { id: "b1-3-2", form: "-(으)ㄴ가 보다", level: "B1", category: "추측/판단" },
  { id: "b1-3-3", form: "-나 보다", level: "B1", category: "추측/판단" },
  { id: "b1-3-4", form: "-(으)ㄹ 텐데", level: "B1", category: "추측/판단" },
  { id: "b1-4-1", form: "-기 위해서", level: "B1", category: "목적/이유" },
  { id: "b1-4-2", form: "-기 때문에", level: "B1", category: "목적/이유" },
  { id: "b1-4-3", form: "-는 덕분에", level: "B1", category: "목적/이유" },
  { id: "b1-4-4", form: "-(으)ㄹ까 봐(걱정/이유)", level: "B1", category: "목적/이유" },
  { id: "b1-4-5", form: "-도록", level: "B1", category: "목적/이유" },
  { id: "b1-5-1", form: "-아/어서 그런지", level: "B1", category: "정도/비교" },
  { id: "b1-5-2", form: "-(으)ㄹ 만하다", level: "B1", category: "정도/비교" },
  { id: "b1-6-1", form: "-아도/어도", level: "B1", category: "양보" },
  { id: "b1-6-2", form: "-지만", level: "B1", category: "양보" },
  { id: "b1-6-3", form: "-(으)ㄴ데(도)", level: "B1", category: "양보" },
  { id: "b1-7-1", form: "-(이)나", level: "B1", category: "나열" },
  { id: "b1-7-2", form: "-거나", level: "B1", category: "나열" },
  { id: "b1-8-1", form: "-게 하다", level: "B1", category: "피동/사동" },
  { id: "b1-9-1", form: "-(으)ㄹ걸 (그랬다)", level: "B1", category: "후회/망설임" },
  { id: "b1-9-2", form: "-(으)ㄹ까 말까 (하다)", level: "B1", category: "후회/망설임" },
  { id: "b1-10-1", form: "-던데(요)", level: "B1", category: "회상/배경" },
  { id: "b1-11-1", form: "-(으)ㄴ/는 척하다", level: "B1", category: "가장/화제" },
  { id: "b1-11-2", form: "-에 대해(서)", level: "B1", category: "가장/화제" },
  { id: "b1-12-1", form: "-는 걸 보니까", level: "B1", category: "기타" },
  { id: "b1-13-1", form: "-(으)ㄴ", level: "B1", category: "관형사형" },
  { id: "b1-13-2", form: "-는", level: "B1", category: "관형사형" },
  { id: "b1-13-3", form: "-(으)ㄹ (필수!)", level: "B1", category: "관형사형" },
  { id: "b2-1-1", form: "-(으)므로", level: "B2", category: "고급 연결" },
  { id: "b2-1-2", form: "-는 통에", level: "B2", category: "고급 연결" },
  { id: "b2-1-3", form: "-(으)ㄹ수록", level: "B2", category: "고급 연결" },
  { id: "b2-1-4", form: "-는 한편", level: "B2", category: "고급 연결" },
  { id: "b2-1-5", form: "-는 반면에", level: "B2", category: "고급 연결" },
  { id: "b2-1-6", form: "-는 대로", level: "B2", category: "고급 연결" },
  { id: "b2-1-7", form: "-는 김에", level: "B2", category: "고급 연결" },
  { id: "b2-1-8", form: "-는 바람에", level: "B2", category: "고급 연결" },
  { id: "b2-1-9", form: "-다가는", level: "B2", category: "고급 연결" },
  { id: "b2-2-1", form: "-게 하다", level: "B2", category: "피동/사동" },
  { id: "b2-2-2", form: "-게 되다", level: "B2", category: "피동/사동" },
  { id: "b2-3-1", form: "-(으)ㄹ 텐데", level: "B2", category: "추측/양태" },
  { id: "b2-3-2", form: "-(으)ㄹ 모양이다", level: "B2", category: "추측/양태" },
  { id: "b2-3-3", form: "-(으)ㄹ 셈이다", level: "B2", category: "추측/양태" },
  { id: "b2-3-4", form: "-(으)ㄹ 리가 없다", level: "B2", category: "추측/양태" },
  { id: "b2-4-1", form: "-(으)ㄹ 겸 (해서)", level: "B2", category: "목적" },
  { id: "b2-5-1", form: "-(으)ㄹ 뿐만 아니라", level: "B2", category: "정도" },
  { id: "b2-5-2", form: "-(으)ㄹ 뿐이다", level: "B2", category: "정도" },
  { id: "b2-5-3", form: "-만 못하다", level: "B2", category: "정도" },
  { id: "b2-5-4", form: "-(으)ㄹ 정도로", level: "B2", category: "정도" },
  { id: "b2-6-1", form: "-는 탓에", level: "B2", category: "이유/근거" },
  { id: "b2-6-2", form: "-(으)ㄴ/는 덕분에", level: "B2", category: "이유/근거" },
  { id: "b2-6-3", form: "-길래", level: "B2", category: "이유/근거" },
  { id: "b2-6-4", form: "-에 따라(서)", level: "B2", category: "이유/근거" },
  { id: "b2-6-5", form: "-에 의해(서)", level: "B2", category: "이유/근거" },
  { id: "b2-7-1", form: "-더라도", level: "B2", category: "양보" },
  { id: "b2-8-1", form: "-(이)야말로", level: "B2", category: "강조/극단" },
  { id: "b2-8-2", form: "마저", level: "B2", category: "강조/극단" },
  { id: "b2-8-3", form: "은/는커녕", level: "B2", category: "강조/극단" },
  { id: "b2-9-1", form: "-더라고(요)", level: "B2", category: "회상/전달" },
  { id: "b2-10-1", form: "-을/를 비롯해서", level: "B2", category: "열거" },
  { id: "b2-11-1", form: "-(으)려다가", level: "B2", category: "의도" },
  { id: "b2-11-2", form: "-(으)려던 참이다", level: "B2", category: "의도" },
  { id: "b2-12-1", form: "-는 사이에", level: "B2", category: "기타" },
  { id: "b2-12-2", form: "-는 수가 있다", level: "B2", category: "기타" },
  { id: "b2-12-3", form: "-는 수밖에 없다", level: "B2", category: "기타" },
  { id: "b2-12-4", form: "-곤 하다", level: "B2", category: "기타" },
  { id: "b2-12-5", form: "-(으)ㄴ 채로", level: "B2", category: "기타" },
  { id: "b2-12-6", form: "-다 보니까", level: "B2", category: "기타" },
  { id: "b2-12-7", form: "-다 보면", level: "B2", category: "기타" },
  { id: "b2-13-1", form: "-(으)ㄴ", level: "B2", category: "관형사형" },
  { id: "b2-13-2", form: "-는", level: "B2", category: "관형사형" },
  { id: "b2-13-3", form: "-(으)ㄹ", level: "B2", category: "관형사형" },
  { id: "c1-1-1", form: "-던", level: "C1", category: "고급 문법" },
  { id: "c1-1-2", form: "-(으)ㄴ 바 있다", level: "C1", category: "고급 문법" },
  { id: "c1-1-3", form: "-(으)로 인해", level: "C1", category: "고급 문법" },
  { id: "c1-2-1", form: "-ㅂ니다/습니다", level: "C1", category: "격식체" },
  { id: "c1-2-2", form: "-는바", level: "C1", category: "격식체" },
  { id: "c1-2-3", form: "-고자", level: "C1", category: "격식체" },
  { id: "c1-3-1", form: "-다고 하다", level: "C1", category: "인용" },
  { id: "c1-3-2", form: "-(으)라고 하다", level: "C1", category: "인용" },
  { id: "c1-3-3", form: "-냐고 하다", level: "C1", category: "인용" },
  { id: "c1-3-4", form: "-자고 하다", level: "C1", category: "인용" },
  { id: "c1-4-1", form: "-더니", level: "C1", category: "회상" },
  { id: "c1-4-2", form: "-더라", level: "C1", category: "회상" },
  { id: "c1-4-3", form: "-던", level: "C1", category: "회상" },
  { id: "c1-4-4", form: "-던가요", level: "C1", category: "회상" },
  { id: "c1-5-1", form: "조차", level: "C1", category: "강조" },
  { id: "c1-6-1", form: "-다거나", level: "C1", category: "나열/선택" },
  { id: "c1-6-2", form: "-든지", level: "C1", category: "나열/선택" },
  { id: "c1-7-1", form: "-듯이", level: "C1", category: "비유" },
  { id: "c1-7-2", form: "-다시피", level: "C1", category: "비유" },
  { id: "c1-8-1", form: "-(으)ㄴ/는 만큼", level: "C1", category: "정도/속성" },
  { id: "c1-8-2", form: "-(으)ㄴ/는 법이다", level: "C1", category: "정도/속성" },
  { id: "c1-9-1", form: "-(이)나 -(이)나 할 것 없이", level: "C1", category: "한정" },
  { id: "c1-10-1", form: "-을/를 통해(서)", level: "C1", category: "기타" },
  { id: "c1-10-2", form: "-에 관해(서)", level: "C1", category: "기타" },
  { id: "c1-10-3", form: "-(으)ㄴ/는들", level: "C1", category: "기타" },
  { id: "c1-10-4", form: "-기 십상이다", level: "C1", category: "기타" },
  { id: "c1-11-1", form: "-(으)ㄴ", level: "C1", category: "관형사형" },
  { id: "c1-11-2", form: "-는", level: "C1", category: "관형사형" },
  { id: "c1-11-3", form: "-(으)ㄹ", level: "C1", category: "관형사형" },
  { id: "c2-1-1", form: "-(으)ㄹ지라도", level: "C2", category: "양보/한정" },
  { id: "c2-1-2", form: "-(으)ㄴ/는 한", level: "C2", category: "양보/한정" },
];

// 문법 목록이 아닌 줄(제목·규칙·어휘·길이 등)과, 문법 줄이 원래 있던 위치를 그대로 담는다.
type TemplateEntry = { type: "literal"; text: string } | { type: "grammar"; catIndex: number; prefix: string; category: string };

const LEVEL_TEMPLATE: Record<CefrLevel, TemplateEntry[]> = {
  A1: [
    { type: "literal", text: "" },
    { type: "literal", text: "   **A1 (TOPIK I 초급 1급)**: " },
    { type: "grammar", catIndex: 1, prefix: "   ", category: "서술/종결" },
    { type: "grammar", catIndex: 2, prefix: "   ", category: "지시/장소" },
    { type: "grammar", catIndex: 3, prefix: "   ", category: "조사" },
    { type: "grammar", catIndex: 4, prefix: "   ", category: "부정" },
    { type: "grammar", catIndex: 5, prefix: "   ", category: "존재" },
    { type: "grammar", catIndex: 6, prefix: "   ", category: "희망" },
    { type: "grammar", catIndex: 7, prefix: "   ", category: "계획/미래" },
    { type: "grammar", catIndex: 8, prefix: "   ", category: "목적" },
    { type: "grammar", catIndex: 9, prefix: "   ", category: "능력/숙련도" },
    { type: "grammar", catIndex: 10, prefix: "   ", category: "의무" },
    { type: "grammar", catIndex: 11, prefix: "   ", category: "이유" },
    { type: "grammar", catIndex: 12, prefix: "   ", category: "조건" },
    { type: "grammar", catIndex: 13, prefix: "   ", category: "대조/나열" },
    { type: "grammar", catIndex: 14, prefix: "   ", category: "시간" },
    { type: "grammar", catIndex: 15, prefix: "   ", category: "진행" },
    { type: "grammar", catIndex: 16, prefix: "   ", category: "높임" },
    { type: "grammar", catIndex: 17, prefix: "   ", category: "요청/권유" },
    { type: "grammar", catIndex: 18, prefix: "   ", category: "도움" },
    { type: "grammar", catIndex: 19, prefix: "   ", category: "시도/권유" },
    { type: "grammar", catIndex: 20, prefix: "   ", category: "수식" },
    { type: "grammar", catIndex: 21, prefix: "   ", category: "단위" },
    { type: "literal", text: "   - 길이: 5-8어절(띄어쓰기로 나눈 덩어리 수)" },
  ],
  A2: [
    { type: "literal", text: "" },
    { type: "literal", text: "   **A2 (TOPIK I 초중급 2급) - 핵심 문법 필수 사용**:" },
    { type: "literal", text: "   **규칙: 문장을 만들 때 아래 나열된 A2 문법 표현 중 하나를 반드시 포함하세요. **" },
    { type: "literal", text: "   " },
    { type: "grammar", catIndex: 1, prefix: "   ", category: "서술/종결" },
    { type: "grammar", catIndex: 2, prefix: "   ", category: "의문(부드러움)" },
    { type: "grammar", catIndex: 3, prefix: "   ", category: "부정" },
    { type: "grammar", catIndex: 4, prefix: "   ", category: "이유(심화)" },
    { type: "grammar", catIndex: 5, prefix: "   ", category: "순서(연속 동작)" },
    { type: "grammar", catIndex: 6, prefix: "   ", category: "동시동작/시간" },
    { type: "grammar", catIndex: 7, prefix: "   ", category: "배경/대조" },
    { type: "grammar", catIndex: 8, prefix: "   ", category: "추측" },
    { type: "grammar", catIndex: 9, prefix: "   ", category: "양태/외견" },
    { type: "grammar", catIndex: 10, prefix: "   ", category: "제안/의지/권유" },
    { type: "grammar", catIndex: 11, prefix: "   ", category: "계획/의도" },
    { type: "grammar", catIndex: 12, prefix: "   ", category: "결심/약속/계획" },
    { type: "grammar", catIndex: 13, prefix: "   ", category: "희망" },
    { type: "grammar", catIndex: 14, prefix: "   ", category: "허락/금지" },
    { type: "grammar", catIndex: 15, prefix: "   ", category: "양보" },
    { type: "grammar", catIndex: 16, prefix: "   ", category: "변화" },
    { type: "grammar", catIndex: 17, prefix: "   ", category: "경험/시도" },
    { type: "grammar", catIndex: 18, prefix: "   ", category: "능력/숙련도" },
    { type: "grammar", catIndex: 19, prefix: "   ", category: "평가" },
    { type: "grammar", catIndex: 20, prefix: "   ", category: "조건/방법" },
    { type: "grammar", catIndex: 21, prefix: "   ", category: "상태/성향" },
    { type: "grammar", catIndex: 22, prefix: "   ", category: "보조용언" },
    { type: "grammar", catIndex: 23, prefix: "   ", category: "나열/선택" },
    { type: "grammar", catIndex: 24, prefix: "   ", category: "조사" },
    { type: "grammar", catIndex: 25, prefix: "   ", category: "비교" },
    { type: "grammar", catIndex: 26, prefix: "   ", category: "부사형" },
    { type: "grammar", catIndex: 27, prefix: "   ", category: "인용(명사)" },
    { type: "grammar", catIndex: 28, prefix: "   ", category: "명사화" },
    { type: "grammar", catIndex: 29, prefix: "   ", category: "관형사형" },
    { type: "grammar", catIndex: 30, prefix: "   ", category: "지식/인지" },
    { type: "literal", text: "   - 길이: 7-10어절(띄어쓰기로 나눈 덩어리 수)" },
  ],
  B1: [
    { type: "literal", text: "" },
    { type: "literal", text: "   **B1 (TOPIK II 중급 3급) - 핵심 문법 필수 사용**:" },
    { type: "literal", text: "   **규칙: 문장을 만들 때 아래 나열된 B1 문법 표현 중 하나를 반드시 포함하세요. 중급 수준의 연결어미와 표현을 사용해주세요.**" },
    { type: "literal", text: "" },
    { type: "literal", text: "   - 어휘: 계획, 경험, 의견, 문제, 환경, 건강, 발전하다, 변화하다, 증가하다, 중요하다" },
    { type: "grammar", catIndex: 1, prefix: "   ", category: "연결어미" },
    { type: "grammar", catIndex: 2, prefix: "   ", category: "간접화법" },
    { type: "grammar", catIndex: 3, prefix: "   ", category: "추측/판단" },
    { type: "grammar", catIndex: 4, prefix: "   ", category: "목적/이유" },
    { type: "grammar", catIndex: 5, prefix: "   ", category: "정도/비교" },
    { type: "grammar", catIndex: 6, prefix: "   ", category: "양보" },
    { type: "grammar", catIndex: 7, prefix: "   ", category: "나열" },
    { type: "grammar", catIndex: 8, prefix: "   ", category: "피동/사동" },
    { type: "grammar", catIndex: 9, prefix: "   ", category: "후회/망설임" },
    { type: "grammar", catIndex: 10, prefix: "   ", category: "회상/배경" },
    { type: "grammar", catIndex: 11, prefix: "   ", category: "가장/화제" },
    { type: "grammar", catIndex: 12, prefix: "   ", category: "기타" },
    { type: "grammar", catIndex: 13, prefix: "   ", category: "관형사형" },
    { type: "literal", text: "   - 길이: 9-13어절(띄어쓰기로 나눈 덩어리 수)" },
  ],
  B2: [
    { type: "literal", text: "" },
    { type: "literal", text: "   **B2 (TOPIK II 중고급 4급) - 핵심 문법 필수 사용**:" },
    { type: "literal", text: "   **규칙: 문장을 만들 때 아래 나열된 B2 문법 표현 중 하나를 반드시 포함하세요. 고급 연결어미와 피동/사동 표현을 적극적으로 사용해주세요.**" },
    { type: "literal", text: "" },
    { type: "literal", text: "   - 어휘: 상황, 현상, 영향, 결과, 원인, 심각하다, 복잡하다, 다양하다, 강조하다" },
    { type: "grammar", catIndex: 1, prefix: "   ", category: "고급 연결" },
    { type: "grammar", catIndex: 2, prefix: "   ", category: "피동/사동" },
    { type: "grammar", catIndex: 3, prefix: "   ", category: "추측/양태" },
    { type: "grammar", catIndex: 4, prefix: "   ", category: "목적" },
    { type: "grammar", catIndex: 5, prefix: "   ", category: "정도" },
    { type: "grammar", catIndex: 6, prefix: "   ", category: "이유/근거" },
    { type: "grammar", catIndex: 7, prefix: "   ", category: "양보" },
    { type: "grammar", catIndex: 8, prefix: "   ", category: "강조/극단" },
    { type: "grammar", catIndex: 9, prefix: "   ", category: "회상/전달" },
    { type: "grammar", catIndex: 10, prefix: "   ", category: "열거" },
    { type: "grammar", catIndex: 11, prefix: "   ", category: "의도" },
    { type: "grammar", catIndex: 12, prefix: "   ", category: "기타" },
    { type: "grammar", catIndex: 13, prefix: "   ", category: "관형사형" },
    { type: "literal", text: "   - 길이: 12-17어절(띄어쓰기로 나눈 덩어리 수)" },
  ],
  C1: [
    { type: "literal", text: "" },
    { type: "literal", text: "   **C1 (TOPIK II 고급 5급 이상) - 핵심 문법 필수 사용**:" },
    { type: "literal", text: "   **규칙: 문장을 만들 때 아래 나열된 C1 문법 표현 중 하나를 반드시 포함하세요. 격식체와 문어체 표현을 사용하여 고급스러운 문장을 만들어주세요.**" },
    { type: "literal", text: "" },
    { type: "literal", text: "   - 어휘: 지속, 체계, 필수, 도출, 분석, 기여하다, 촉진하다, 저해하다, 효율적, 합리적" },
    { type: "grammar", catIndex: 1, prefix: "   ", category: "고급 문법" },
    { type: "grammar", catIndex: 2, prefix: "   ", category: "격식체" },
    { type: "grammar", catIndex: 3, prefix: "   ", category: "인용" },
    { type: "grammar", catIndex: 4, prefix: "   ", category: "회상" },
    { type: "grammar", catIndex: 5, prefix: "   ", category: "강조" },
    { type: "grammar", catIndex: 6, prefix: "   ", category: "나열/선택" },
    { type: "grammar", catIndex: 7, prefix: "   ", category: "비유" },
    { type: "grammar", catIndex: 8, prefix: "   ", category: "정도/속성" },
    { type: "grammar", catIndex: 9, prefix: "   ", category: "한정" },
    { type: "grammar", catIndex: 10, prefix: "   ", category: "기타" },
    { type: "grammar", catIndex: 11, prefix: "   ", category: "관형사형" },
    { type: "literal", text: "   - 길이: 16-24어절(띄어쓰기로 나눈 덩어리 수)" },
  ],
  C2: [
    { type: "literal", text: "" },
    { type: "literal", text: "   **C2 (최고급) - 핵심 문법 필수 사용**:" },
    { type: "literal", text: "   **규칙: 가능한 한 복잡하고 정교한 문장 구조를 사용하세요. 학술적이거나 전문적인 맥락의 어휘와 표현을 적극 사용해주세요.**" },
    { type: "literal", text: "" },
    { type: "literal", text: "   - 사용 가능: 학술 용어, 전문 어휘, 관용 표현" },
    { type: "grammar", catIndex: 1, prefix: "   ", category: "양보/한정" },
    { type: "literal", text: "   - 문법: 매우 복잡한 구조, 격식체" },
    { type: "literal", text: "   - 길이: 16-28어절(띄어쓰기로 나눈 덩어리 수)" },
  ],
};

/** DIFFICULTY_GUIDES[level]과 동일한 문자열을 GRAMMAR_ITEMS로부터 만든다. */
export function renderGuide(level: CefrLevel): string {
  const itemsByCat = new Map<number, string[]>();
  for (const it of GRAMMAR_ITEMS) {
    if (it.level !== level) continue;
    const catIndex = Number(it.id.split("-")[1]);
    const list = itemsByCat.get(catIndex) ?? [];
    list.push(it.form);
    itemsByCat.set(catIndex, list);
  }
  return LEVEL_TEMPLATE[level]
    .map((entry) =>
      entry.type === "literal"
        ? entry.text
        : `${entry.prefix}- ${entry.category}: ${(itemsByCat.get(entry.catIndex) ?? []).join(", ")}`
    )
    .join("\n");
}
