// AI 생성 프롬프트(generate-quiz)의 DIFFICULTY_GUIDES를 구조화한 것.
// 이 파일이 유일한 문법 기준이다 — 항목 추가·급수 변경은 여기서만 한다.
// GRAMMAR_ITEMS와 LEVEL_TEMPLATE로부터 renderGuide()가 기존 DIFFICULTY_GUIDES 문자열을
// 한 글자도 틀리지 않게 재생성한다(검증: scratchpad/extract-grammar.mjs로 byte-exact 비교).

export type CefrLevel = "A1" | "A2" | "B1" | "B2" | "C1" | "C2";

export type GrammarItem = {
  id: string;
  form: string;
  level: CefrLevel;
  category: string;
};

// 문장 은행 등에서 참고할 급수별 목표 문장 길이. DIFFICULTY_GUIDES의 "길이:" 줄과 같은 값이다.
//
// 단위는 "단어"가 아니라 "어절"이다 — measure-baseline.ts가 공백 분할(split(/\s+/))로 세고
// 있었고, 실측 결과(A1 5.1 ± 1.2 등)가 기존 숫자와 맞아떨어져 라벨만 잘못돼 있었음을 확인했다.
// A2/B1/B2는 실측 SD(1.5 → 1.8 → 2.6)에 맞춰 범위 폭도 3 → 4 → 5로 넓혔다(SD가 클수록
// 실제 편차가 크므로 범위를 좁게 잡으면 정상 문장도 자주 벗어난다). A1/C1/C2는 실측이
// 범위 안이었거나(A1) 아직 측정하지 않아(C1/C2) 숫자는 그대로 두고 라벨만 고쳤다.
// 2차 조정(2026-08-21): 1차 조정이 하한을 실측 평균 근처에 둬서(예: A2 하한 7 = 평균
// 7.00) 평균보다 짧은 절반 가까이가 구조적으로 "미달" 판정을 받는 결함이 있었다.
// 평균을 가운데 두는 방식(평균 ∓ 1표준편차, 정규분포 기준 약 68% 포괄)으로 다시 잡았다.
// A1/A2/B1/B2는 실측(2026-08-07 baseline) 기준: A1 5.16±1.22, A2 7.00±1.51,
// B1 9.40±1.8, B2 12.12±2.6. C1/C2는 실사용 0건이라 측정 데이터가 없어 선생님이
// 직접 지정(B2 상한 15 → C1 12-17 → C2 13-18로 사다리가 이어지게).
export const LEVEL_SENTENCE_LENGTH: Record<CefrLevel, string> = {
  A1: "4-6어절(띄어쓰기로 나눈 덩어리 수)",
  A2: "5-9어절(띄어쓰기로 나눈 덩어리 수)",
  B1: "8-11어절(띄어쓰기로 나눈 덩어리 수)",
  B2: "10-15어절(띄어쓰기로 나눈 덩어리 수)",
  C1: "12-17어절(띄어쓰기로 나눈 덩어리 수)",
  C2: "13-18어절(띄어쓰기로 나눈 덩어리 수)",
};

export const GRAMMAR_ITEMS: GrammarItem[] = [
  { id: "a1-1-1", form: "-이에요/예요", level: "A1", category: "서술/종결" },
  { id: "a1-1-2", form: "-아/어요", level: "A1", category: "서술/종결" },
  { id: "a1-1-3", form: "-았/었어요(과거)", level: "A1", category: "서술/종결" },
  { id: "a1-1-4", form: "-지요?(확인)", level: "A1", category: "서술/종결" },
  { id: "a1-2-1", form: "이거/그거/저거", level: "A1", category: "지시/장소" },
  { id: "a1-2-2", form: "여기/거기/저기", level: "A1", category: "지시/장소" },
  { id: "a1-3-1", form: "은/는(주제)", level: "A1", category: "조사" },
  { id: "a1-3-2", form: "이/가(주어/아니다)", level: "A1", category: "조사" },
  { id: "a1-3-3", form: "을/를(목적)", level: "A1", category: "조사" },
  { id: "a1-3-4", form: "도(포함)", level: "A1", category: "조사" },
  { id: "a1-3-5", form: "에(위치/시간)", level: "A1", category: "조사" },
  { id: "a1-3-6", form: "에서(장소/출발)", level: "A1", category: "조사" },
  { id: "a1-3-7", form: "부터&까지", level: "A1", category: "조사" },
  { id: "a1-3-8", form: "(으)로(방향/수단)", level: "A1", category: "조사" },
  { id: "a1-3-9", form: "하고&와/과(나열)", level: "A1", category: "조사" },
  { id: "a1-3-10", form: "만(한정)", level: "A1", category: "조사" },
  { id: "a1-3-11", form: "한테&께(대상)", level: "A1", category: "조사" },
  { id: "a1-3-12", form: "의(소유)", level: "A1", category: "조사" },
  { id: "a1-3-13", form: "위&아래&앞&뒤", level: "A1", category: "조사" },
  { id: "a1-4-1", form: "안(부정)", level: "A1", category: "부정" },
  { id: "a1-4-2", form: "못(불가능)", level: "A1", category: "부정" },
  { id: "a1-4-3", form: "이/가 아니다", level: "A1", category: "부정" },
  { id: "a1-5-1", form: "있어요/없어요", level: "A1", category: "존재" },
  { id: "a1-6-1", form: "-고 싶다", level: "A1", category: "희망" },
  { id: "a1-6-2", form: "-고 싶어 하다", level: "A1", category: "희망" },
  { id: "a1-7-1", form: "-(으)ㄹ 거예요(미래)", level: "A1", category: "계획/미래" },
  { id: "a1-7-2", form: "-(으)려고 해요", level: "A1", category: "계획/미래" },
  { id: "a1-8-1", form: "-(으)러 가다/오다", level: "A1", category: "목적" },
  { id: "a1-9-1", form: "-(으)ㄹ 수 있다/없다", level: "A1", category: "능력/숙련도" },
  { id: "a1-9-2", form: "못하다/잘하다/잘 못하다", level: "A1", category: "능력/숙련도" },
  { id: "a1-10-1", form: "-아야/어야 해요", level: "A1", category: "의무" },
  { id: "a1-10-2", form: "-아야/어야 되다", level: "A1", category: "의무" },
  { id: "a1-11-1", form: "-아서/어서(이유)", level: "A1", category: "이유" },
  { id: "a1-12-1", form: "-(으)면", level: "A1", category: "조건" },
  { id: "a1-13-1", form: "-지만", level: "A1", category: "대조/나열" },
  { id: "a1-13-2", form: "근데", level: "A1", category: "대조/나열" },
  { id: "a1-13-3", form: "-고(동작 나열)", level: "A1", category: "대조/나열" },
  { id: "a1-14-1", form: "-(으)ㄹ 때", level: "A1", category: "시간" },
  { id: "a1-15-1", form: "-고 있다", level: "A1", category: "진행" },
  { id: "a1-16-1", form: "-(으)시다", level: "A1", category: "높임" },
  { id: "a1-16-2", form: "-(이)세요", level: "A1", category: "높임" },
  { id: "a1-17-1", form: "-(으)세요", level: "A1", category: "요청/권유" },
  { id: "a1-17-2", form: "-지 마세요", level: "A1", category: "요청/권유" },
  { id: "a1-17-3", form: "-(으)ㄹ까요?(권유)", level: "A1", category: "요청/권유" },
  { id: "a1-17-4", form: "N 주세요", level: "A1", category: "요청/권유" },
  { id: "a1-18-1", form: "-아/어 주다", level: "A1", category: "도움" },
  { id: "a1-18-2", form: "-아/어 드릴까요?", level: "A1", category: "도움" },
  { id: "a1-18-3", form: "-아/어 드릴게요", level: "A1", category: "도움" },
  { id: "a1-18-4", form: "-아/어 주시겠어요?", level: "A1", category: "도움" },
  { id: "a1-19-1", form: "-아/어 보세요", level: "A1", category: "시도/권유" },
  { id: "a1-20-1", form: "형용사+-(으)ㄴ", level: "A1", category: "수식" },
  { id: "a1-21-1", form: "개/병/잔/그릇", level: "A1", category: "단위" },
  { id: "a2-1-1", form: "-네요(감탄)", level: "A2", category: "서술/종결" },
  { id: "a2-2-1", form: "-(으)ㄴ가요?", level: "A2", category: "의문(부드러움)" },
  { id: "a2-2-2", form: "-나요?", level: "A2", category: "의문(부드러움)" },
  { id: "a2-2-3", form: "N인가요?", level: "A2", category: "의문(부드러움)" },
  { id: "a2-3-1", form: "-지 않다(장형 부정)", level: "A2", category: "부정" },
  { id: "a2-4-1", form: "-(으)니까", level: "A2", category: "이유(심화)" },
  { id: "a2-4-2", form: "-기 때문에", level: "A2", category: "이유(심화)" },
  { id: "a2-4-3", form: "N 때문에", level: "A2", category: "이유(심화)" },
  { id: "a2-4-4", form: "N(이)라서", level: "A2", category: "이유(심화)" },
  { id: "a2-5-1", form: "-아서/어서(순서)", level: "A2", category: "순서(연속 동작)" },
  { id: "a2-5-2", form: "-고 나서", level: "A2", category: "순서(연속 동작)" },
  { id: "a2-6-1", form: "-(으)면서", level: "A2", category: "동시동작/시간" },
  { id: "a2-6-2", form: "-는 동안에", level: "A2", category: "동시동작/시간" },
  { id: "a2-6-3", form: "N 동안", level: "A2", category: "동시동작/시간" },
  { id: "a2-6-4", form: "-다가(전환)", level: "A2", category: "동시동작/시간" },
  { id: "a2-6-5", form: "-(으)ㄴ 지(경과)", level: "A2", category: "동시동작/시간" },
  { id: "a2-6-6", form: "-기 전에", level: "A2", category: "동시동작/시간" },
  { id: "a2-6-7", form: "-(으)ㄴ 후에", level: "A2", category: "동시동작/시간" },
  { id: "a2-6-8", form: "-았/었을 때", level: "A2", category: "동시동작/시간" },
  { id: "a2-7-1", form: "-는데/-(으)ㄴ데(연결)", level: "A2", category: "배경/대조" },
  { id: "a2-7-2", form: "-(으)ㄴ데요", level: "A2", category: "배경/대조" },
  { id: "a2-7-3", form: "-는데요", level: "A2", category: "배경/대조" },
  { id: "a2-7-4", form: "N인데요", level: "A2", category: "배경/대조" },
  { id: "a2-7-5", form: "형용사+-(으)ㄴ데", level: "A2", category: "배경/대조" },
  { id: "a2-8-1", form: "-(으)ㄹ까요?(추측)", level: "A2", category: "추측" },
  { id: "a2-8-2", form: "-(으)ㄹ 거예요(추측)", level: "A2", category: "추측" },
  { id: "a2-8-3", form: "-(으)ㄹ 것 같다", level: "A2", category: "추측" },
  { id: "a2-8-4", form: "-(으)ㄴ/는 것 같다", level: "A2", category: "추측" },
  { id: "a2-8-5", form: "N인 것 같다", level: "A2", category: "추측" },
  { id: "a2-9-1", form: "-아/어 보이다", level: "A2", category: "양태/외견" },
  { id: "a2-9-2", form: "-(으)ㄹ지 모르겠다", level: "A2", category: "양태/외견" },
  { id: "a2-10-1", form: "-(으)ㅂ시다", level: "A2", category: "제안/의지/권유" },
  { id: "a2-10-2", form: "-(으)ㄹ래요", level: "A2", category: "제안/의지/권유" },
  { id: "a2-10-3", form: "-(으)ㄹ게요", level: "A2", category: "제안/의지/권유" },
  { id: "a2-10-4", form: "-겠어요", level: "A2", category: "제안/의지/권유" },
  { id: "a2-10-5", form: "-는 게 좋겠다", level: "A2", category: "제안/의지/권유" },
  { id: "a2-10-6", form: "-는 게 어때요?", level: "A2", category: "제안/의지/권유" },
  { id: "a2-11-1", form: "-(으)려고", level: "A2", category: "계획/의도" },
  { id: "a2-12-1", form: "-기로 하다", level: "A2", category: "결심/약속/계획" },
  { id: "a2-12-2", form: "-(으)ㄹ까 하다", level: "A2", category: "결심/약속/계획" },
  { id: "a2-13-1", form: "-았/었으면 좋겠다", level: "A2", category: "희망" },
  { id: "a2-14-1", form: "-아도/어도 되다", level: "A2", category: "허락/금지" },
  { id: "a2-14-2", form: "-(으)면 안 되다", level: "A2", category: "허락/금지" },
  { id: "a2-15-1", form: "-아도/어도", level: "A2", category: "양보" },
  { id: "a2-15-2", form: "-기는 하지만", level: "A2", category: "양보" },
  { id: "a2-16-1", form: "-게 되다", level: "A2", category: "변화" },
  { id: "a2-16-2", form: "-아/어지다", level: "A2", category: "변화" },
  { id: "a2-17-1", form: "-(으)ㄴ 적이 있다/없다", level: "A2", category: "경험/시도" },
  { id: "a2-17-2", form: "-아/어 보다", level: "A2", category: "경험/시도" },
  { id: "a2-17-3", form: "-(으)ㄹ 뻔하다", level: "A2", category: "경험/시도" },
  { id: "a2-18-1", form: "-(으)ㄹ 줄 알다/모르다", level: "A2", category: "능력/숙련도" },
  { id: "a2-19-1", form: "-기(가) 쉽다/어렵다", level: "A2", category: "평가" },
  { id: "a2-20-1", form: "-(으)려면", level: "A2", category: "조건/방법" },
  { id: "a2-20-2", form: "-(으)면 되다", level: "A2", category: "조건/방법" },
  { id: "a2-20-3", form: "-(으)ㄹ 테니까", level: "A2", category: "조건/방법" },
  { id: "a2-21-1", form: "-는 중이다", level: "A2", category: "상태/성향" },
  { id: "a2-21-2", form: "N 중이다", level: "A2", category: "상태/성향" },
  { id: "a2-21-3", form: "-(으)ㄴ/는 편이다", level: "A2", category: "상태/성향" },
  { id: "a2-22-1", form: "-아/어 있다(상태 지속)", level: "A2", category: "보조용언" },
  { id: "a2-22-2", form: "-아/어 놓다", level: "A2", category: "보조용언" },
  { id: "a2-22-3", form: "-아/어 버리다", level: "A2", category: "보조용언" },
  { id: "a2-22-4", form: "-아/어다 주다", level: "A2", category: "보조용언" },
  { id: "a2-23-1", form: "-거나", level: "A2", category: "나열/선택" },
  { id: "a2-23-2", form: "(이)나(명사 나열)", level: "A2", category: "나열/선택" },
  { id: "a2-24-1", form: "밖에", level: "A2", category: "조사" },
  { id: "a2-24-2", form: "마다", level: "A2", category: "조사" },
  { id: "a2-24-3", form: "처럼&같이", level: "A2", category: "조사" },
  { id: "a2-24-4", form: "중에(서)", level: "A2", category: "조사" },
  { id: "a2-24-5", form: "N 대신", level: "A2", category: "조사" },
  { id: "a2-25-1", form: "보다 더", level: "A2", category: "비교" },
  { id: "a2-26-1", form: "형용사+-게", level: "A2", category: "부사형" },
  { id: "a2-27-1", form: "N(이)라고 하다", level: "A2", category: "인용(명사)" },
  { id: "a2-28-1", form: "-는 것", level: "A2", category: "명사화" },
  { id: "a2-29-1", form: "(동사)+-는", level: "A2", category: "관형사형" },
  { id: "a2-29-2", form: "(동사)+-(으)ㄴ", level: "A2", category: "관형사형" },
  { id: "a2-29-3", form: "(동사)+-(으)ㄹ", level: "A2", category: "관형사형" },
  { id: "a2-30-1", form: "-(으)ㄴ/는지 알다", level: "A2", category: "지식/인지" },
  { id: "a2-30-2", form: "N인지 알다/모르다", level: "A2", category: "지식/인지" },
  { id: "b1-1-1", form: "-느라고", level: "B1", category: "연결어미" },
  { id: "b1-1-2", form: "-는 대신에", level: "B1", category: "연결어미" },
  { id: "b1-1-3", form: "-다가", level: "B1", category: "연결어미" },
  { id: "b1-1-4", form: "-더니", level: "B1", category: "연결어미" },
  { id: "b1-1-5", form: "-던", level: "B1", category: "연결어미" },
  { id: "b1-2-1", form: "-다고 하다", level: "B1", category: "간접화법" },
  { id: "b1-2-2", form: "-ㄴ/는다고 하다", level: "B1", category: "간접화법" },
  { id: "b1-2-3", form: "-았/었다고 하다", level: "B1", category: "간접화법" },
  { id: "b1-2-4", form: "-(으)ㄹ 거라고 하다", level: "B1", category: "간접화법" },
  { id: "b1-2-5", form: "-자고 하다", level: "B1", category: "간접화법" },
  { id: "b1-2-6", form: "-냐고 하다", level: "B1", category: "간접화법" },
  { id: "b1-2-7", form: "-(으)라고 하다", level: "B1", category: "간접화법" },
  { id: "b1-2-8", form: "-대(요)", level: "B1", category: "간접화법(축약)" },
  { id: "b1-2-9", form: "-ㄴ/는대(요)", level: "B1", category: "간접화법(축약)" },
  { id: "b1-2-10", form: "(이)래(요)", level: "B1", category: "간접화법(축약)" },
  { id: "b1-2-11", form: "-다니(요)", level: "B1", category: "간접화법(놀람)" },
  { id: "b1-2-12", form: "(이)라니(요)", level: "B1", category: "간접화법(놀람)" },
  { id: "b1-2-13", form: "-다니까(요)", level: "B1", category: "간접화법(강조)" },
  { id: "b1-2-14", form: "-ㄴ/는다니까(요)", level: "B1", category: "간접화법(강조)" },
  { id: "b1-2-15", form: "(이)라니까(요)", level: "B1", category: "간접화법(강조)" },
  { id: "b1-2-16", form: "-다고(요)", level: "B1", category: "간접화법(확인)" },
  { id: "b1-2-17", form: "-ㄴ/는다고(요)", level: "B1", category: "간접화법(확인)" },
  { id: "b1-2-18", form: "(이)라고(요)", level: "B1", category: "간접화법(확인)" },
  { id: "b1-2-19", form: "-다고 들었다", level: "B1", category: "간접화법(전문)" },
  { id: "b1-2-20", form: "-ㄴ/는다고 들었다", level: "B1", category: "간접화법(전문)" },
  { id: "b1-2-21", form: "(이)라고 들었다", level: "B1", category: "간접화법(전문)" },
  { id: "b1-3-1", form: "-(으)ㄴ/는 것 같다", level: "B1", category: "추측/판단" },
  { id: "b1-3-2", form: "-(으)ㄴ가 보다", level: "B1", category: "추측/판단" },
  { id: "b1-3-3", form: "-나 보다", level: "B1", category: "추측/판단" },
  { id: "b1-3-4", form: "-(으)ㄹ 텐데", level: "B1", category: "추측/판단" },
  { id: "b1-4-1", form: "-기 위해서", level: "B1", category: "목적/이유" },
  { id: "b1-4-2", form: "-기 때문에", level: "B1", category: "목적/이유" },
  { id: "b1-4-3", form: "-는 덕분에", level: "B1", category: "목적/이유" },
  { id: "b1-4-4", form: "-(으)ㄹ까 봐(걱정/이유)", level: "B1", category: "목적/이유" },
  { id: "b1-4-5", form: "-도록", level: "B1", category: "목적/이유" },
  { id: "b1-5-1", form: "-아/어서 그런지", level: "B1", category: "정도/비교" },
  { id: "b1-5-2", form: "-(으)ㄹ 만하다", level: "B1", category: "정도/비교" },
  { id: "b1-6-1", form: "-아도/어도", level: "B1", category: "양보" },
  { id: "b1-6-2", form: "-지만", level: "B1", category: "양보" },
  { id: "b1-6-3", form: "-(으)ㄴ데(도)", level: "B1", category: "양보" },
  { id: "b1-7-1", form: "-(이)나", level: "B1", category: "나열" },
  { id: "b1-7-2", form: "-거나", level: "B1", category: "나열" },
  { id: "b1-8-1", form: "-게 하다", level: "B1", category: "피동/사동" },
  { id: "b1-9-1", form: "-(으)ㄹ걸 (그랬다)", level: "B1", category: "후회/망설임" },
  { id: "b1-9-2", form: "-(으)ㄹ까 말까 (하다)", level: "B1", category: "후회/망설임" },
  { id: "b1-10-1", form: "-던데(요)", level: "B1", category: "회상/배경" },
  { id: "b1-11-1", form: "-(으)ㄴ/는 척하다", level: "B1", category: "가장/화제" },
  { id: "b1-11-2", form: "-에 대해(서)", level: "B1", category: "가장/화제" },
  { id: "b1-12-1", form: "-는 걸 보니까", level: "B1", category: "기타" },
  { id: "b1-13-1", form: "-(으)ㄴ", level: "B1", category: "관형사형" },
  { id: "b1-13-2", form: "-는", level: "B1", category: "관형사형" },
  { id: "b1-13-3", form: "-(으)ㄹ (필수!)", level: "B1", category: "관형사형" },
  { id: "b1-14-1", form: "-다/-ㄴ다/-는다(문어체)", level: "B1", category: "서술/종결" },
  { id: "b1-14-2", form: "N(이)다(문어체)", level: "B1", category: "서술/종결" },
  { id: "b1-2-22", form: "-느냐고 하다[묻다]", level: "B1", category: "간접화법" },
  { id: "b1-3-5", form: "-(으)ㄴ 모양이다", level: "B1", category: "추측/판단" },
  { id: "b1-3-6", form: "-는 모양이다", level: "B1", category: "추측/판단" },
  { id: "b1-3-7", form: "인 모양이다", level: "B1", category: "추측/판단" },
  { id: "b1-3-8", form: "인가 보다", level: "B1", category: "추측/판단" },
  { id: "b1-3-9", form: "-(으)ㄹ 줄 몰랐다", level: "B1", category: "추측/판단" },
  { id: "b1-3-10", form: "얼마나 A-(으)ㄴ지/V-는지 모르다", level: "B1", category: "추측/판단" },
  { id: "b1-3-11", form: "-(으)ㄹ걸(요)", level: "B1", category: "추측/판단" },
  { id: "b1-3-12", form: "-아/어야 할 텐데(요)", level: "B1", category: "추측/판단" },
  { id: "b1-4-6", form: "을/를 위해(서)", level: "B1", category: "목적/이유" },
  { id: "b1-4-7", form: "하도 A/V-아/어서", level: "B1", category: "목적/이유" },
  { id: "b1-4-8", form: "-도록 하다", level: "B1", category: "목적/이유" },
  { id: "b1-6-4", form: "-는데도", level: "B1", category: "양보" },
  { id: "b1-6-5", form: "-는데도 불구하고", level: "B1", category: "양보" },
  { id: "b1-6-6", form: "-(으)ㄴ데도 불구하고", level: "B1", category: "양보" },
  { id: "b1-6-7", form: "인데도 불구하고", level: "B1", category: "양보" },
  { id: "b1-6-8", form: "인데도", level: "B1", category: "양보" },
  { id: "b1-6-9", form: "아무리 A/V-아/어도", level: "B1", category: "양보" },
  { id: "b1-8-2", form: "-이/히/리/기-(피동)", level: "B1", category: "피동/사동" },
  { id: "b1-8-3", form: "-이/히/리/기/우-(사동)", level: "B1", category: "피동/사동" },
  { id: "b1-9-3", form: "-았/었어야 했는데", level: "B1", category: "후회/망설임" },
  { id: "b1-11-3", form: "N에 대한 N", level: "B1", category: "가장/화제" },
  { id: "b1-12-2", form: "누구나, 언제나, 어디나, 무엇이나, 무슨 N(이)나", level: "B1", category: "기타" },
  { id: "b1-12-3", form: "무슨 N(이)든(지)", level: "B1", category: "기타" },
  { id: "b1-12-4", form: "무엇이든(지)", level: "B1", category: "기타" },
  { id: "b1-12-5", form: "아무 N도", level: "B1", category: "기타" },
  { id: "b1-12-6", form: "(이)라도", level: "B1", category: "기타" },
  { id: "b1-12-7", form: "만 하다", level: "B1", category: "기타" },
  { id: "b1-12-8", form: "-기로 유명하다", level: "B1", category: "기타" },
  { id: "b1-12-9", form: "(으)로 유명하다", level: "B1", category: "기타" },
  { id: "b1-12-10", form: "-지 않으면 안 되다", level: "B1", category: "기타" },
  { id: "b1-12-11", form: "N(이)라고 (해서) 다 A(으)ㄴ/V-는 것은 아니다", level: "B1", category: "기타" },
  { id: "b1-15-1", form: "-고 보니", level: "B1", category: "완료/회상" },
  { id: "b1-15-2", form: "-아/어 보니(까)", level: "B1", category: "완료/회상" },
  { id: "b1-15-3", form: "-았/었다가", level: "B1", category: "완료/회상" },
  { id: "b1-15-4", form: "-았/었더니", level: "B1", category: "완료/회상" },
  { id: "b1-15-5", form: "-았/었던", level: "B1", category: "완료/회상" },
  { id: "b1-15-6", form: "-자마자", level: "B1", category: "완료/회상" },
  { id: "b1-15-7", form: "-고 말다", level: "B1", category: "완료/회상" },
  { id: "b1-16-1", form: "-(으)ㄹ 생각[계획, 예정]이다", level: "B1", category: "계획/의도" },
  { id: "b1-16-2", form: "-(으)ㄹ 생각도 못 하다", level: "B1", category: "계획/의도" },
  { id: "b1-16-3", form: "-(으)려면 멀었다", level: "B1", category: "계획/의도" },
  { id: "b1-16-4", form: "-는 길에", level: "B1", category: "계획/의도" },
  { id: "b1-16-5", form: "-아/어야겠다", level: "B1", category: "계획/의도" },
  { id: "b1-17-1", form: "-ㄴ/는다면", level: "B1", category: "조건/가정" },
  { id: "b1-17-2", form: "-다면", level: "B1", category: "조건/가정" },
  { id: "b1-17-3", form: "A/V-(으)면 A/V-(으)ㄹ수록", level: "B1", category: "조건/가정" },
  { id: "b1-17-4", form: "이어야/여야", level: "B1", category: "조건/가정" },
  { id: "b1-17-5", form: "(이)라면", level: "B1", category: "조건/가정" },
  { id: "b1-17-6", form: "-아/어야", level: "B1", category: "조건/가정" },
  { id: "b1-18-1", form: "-거든요", level: "B1", category: "구어체 종결" },
  { id: "b1-18-2", form: "(이)거든(요)", level: "B1", category: "구어체 종결" },
  { id: "b1-18-3", form: "-잖아(요)", level: "B1", category: "구어체 종결" },
  { id: "b1-18-4", form: "-지 그래(요)?", level: "B1", category: "구어체 종결" },
  { id: "b1-18-5", form: "-아/어하다", level: "B1", category: "구어체 종결" },
  { id: "b2-1-1", form: "-(으)므로", level: "B2", category: "고급 연결" },
  { id: "b2-1-2", form: "-는 통에", level: "B2", category: "고급 연결" },
  { id: "b2-1-3", form: "-(으)ㄹ수록", level: "B2", category: "고급 연결" },
  { id: "b2-1-4", form: "-는 한편", level: "B2", category: "고급 연결" },
  { id: "b2-1-5", form: "-는 반면에", level: "B2", category: "고급 연결" },
  { id: "b2-1-6", form: "-는 대로", level: "B2", category: "고급 연결" },
  { id: "b2-1-7", form: "-는 김에", level: "B2", category: "고급 연결" },
  { id: "b2-1-8", form: "-는 바람에", level: "B2", category: "고급 연결" },
  { id: "b2-1-9", form: "-다가는", level: "B2", category: "고급 연결" },
  { id: "b2-2-1", form: "-게 하다", level: "B2", category: "피동/사동" },
  { id: "b2-2-2", form: "-게 되다", level: "B2", category: "피동/사동" },
  { id: "b2-3-1", form: "-(으)ㄹ 텐데", level: "B2", category: "추측/양태" },
  { id: "b2-3-2", form: "-(으)ㄹ 모양이다", level: "B2", category: "추측/양태" },
  { id: "b2-3-3", form: "-(으)ㄹ 셈이다", level: "B2", category: "추측/양태" },
  { id: "b2-3-4", form: "-(으)ㄹ 리가 없다", level: "B2", category: "추측/양태" },
  { id: "b2-4-1", form: "-(으)ㄹ 겸 (해서)", level: "B2", category: "목적" },
  { id: "b2-5-1", form: "-(으)ㄹ 뿐만 아니라", level: "B2", category: "정도" },
  { id: "b2-5-2", form: "-(으)ㄹ 뿐이다", level: "B2", category: "정도" },
  { id: "b2-5-3", form: "-만 못하다", level: "B2", category: "정도" },
  { id: "b2-5-4", form: "-(으)ㄹ 정도로", level: "B2", category: "정도" },
  { id: "b2-6-1", form: "-는 탓에", level: "B2", category: "이유/근거" },
  { id: "b2-6-2", form: "-(으)ㄴ/는 덕분에", level: "B2", category: "이유/근거" },
  { id: "b2-6-3", form: "-길래", level: "B2", category: "이유/근거" },
  { id: "b2-6-4", form: "-에 따라(서)", level: "B2", category: "이유/근거" },
  { id: "b2-6-5", form: "-에 의해(서)", level: "B2", category: "이유/근거" },
  { id: "b2-7-1", form: "-더라도", level: "B2", category: "양보" },
  { id: "b2-8-1", form: "-(이)야말로", level: "B2", category: "강조/극단" },
  { id: "b2-8-2", form: "마저", level: "B2", category: "강조/극단" },
  { id: "b2-8-3", form: "은/는커녕", level: "B2", category: "강조/극단" },
  { id: "b2-9-1", form: "-더라고(요)", level: "B2", category: "회상/전달" },
  { id: "b2-10-1", form: "-을/를 비롯해서", level: "B2", category: "열거" },
  { id: "b2-11-1", form: "-(으)려다가", level: "B2", category: "의도" },
  { id: "b2-11-2", form: "-(으)려던 참이다", level: "B2", category: "의도" },
  { id: "b2-12-1", form: "-는 사이에", level: "B2", category: "기타" },
  { id: "b2-12-2", form: "-는 수가 있다", level: "B2", category: "기타" },
  { id: "b2-12-3", form: "-는 수밖에 없다", level: "B2", category: "기타" },
  { id: "b2-12-4", form: "-곤 하다", level: "B2", category: "기타" },
  { id: "b2-12-5", form: "-(으)ㄴ 채로", level: "B2", category: "기타" },
  { id: "b2-12-6", form: "-다 보니까", level: "B2", category: "기타" },
  { id: "b2-12-7", form: "-다 보면", level: "B2", category: "기타" },
  { id: "b2-13-1", form: "-(으)ㄴ", level: "B2", category: "관형사형" },
  { id: "b2-13-2", form: "-는", level: "B2", category: "관형사형" },
  { id: "b2-13-3", form: "-(으)ㄹ", level: "B2", category: "관형사형" },
  { id: "b2-3-5", form: "-ㄴ/는다 싶다", level: "B2", category: "추측/양태" },
  { id: "b2-3-6", form: "-(으)ㄴ 듯하다", level: "B2", category: "추측/양태" },
  { id: "b2-3-7", form: "-(으)ㄴ 셈이다", level: "B2", category: "추측/양태" },
  { id: "b2-3-8", form: "-(으)ㄹ 게 뻔하다", level: "B2", category: "추측/양태" },
  { id: "b2-3-9", form: "-(으)ㄹ지도 모르다", level: "B2", category: "추측/양태" },
  { id: "b2-3-10", form: "-는 듯하다", level: "B2", category: "추측/양태" },
  { id: "b2-3-11", form: "-는 셈이다", level: "B2", category: "추측/양태" },
  { id: "b2-3-12", form: "-다 싶다", level: "B2", category: "추측/양태" },
  { id: "b2-7-2", form: "-(으)나", level: "B2", category: "양보" },
  { id: "b2-7-3", form: "-(으)나 마나", level: "B2", category: "양보" },
  { id: "b2-14-1", form: "-ㄴ/는다고 보다", level: "B2", category: "인용/전언" },
  { id: "b2-14-2", form: "-다고 보다", level: "B2", category: "인용/전언" },
  { id: "b2-14-3", form: "-ㄴ/는다기보다는", level: "B2", category: "인용/전언" },
  { id: "b2-14-4", form: "-다기보다는", level: "B2", category: "인용/전언" },
  { id: "b2-14-5", form: "-ㄴ/는다더니", level: "B2", category: "인용/전언" },
  { id: "b2-14-6", form: "-다더니", level: "B2", category: "인용/전언" },
  { id: "b2-14-7", form: "-ㄴ/는다면서(요)?", level: "B2", category: "인용/전언" },
  { id: "b2-14-8", form: "-다면서(요)?", level: "B2", category: "인용/전언" },
  { id: "b2-14-9", form: "에 의하면", level: "B2", category: "인용/전언" },
  { id: "b2-14-10", form: "A-다는 것은 N에서/N(으)로 알 수 있다", level: "B2", category: "인용/전언" },
  { id: "b2-14-11", form: "A-다는 N, V-ㄴ/는다는 N", level: "B2", category: "인용/전언" },
  { id: "b2-14-12", form: "N(이)라는 N", level: "B2", category: "인용/전언" },
  { id: "b2-14-13", form: "N은/는 A-다는 것이다[점이다]", level: "B2", category: "인용/전언" },
  { id: "b2-14-14", form: "N은/는 V-ㄴ/는다는 것이다[점이다]", level: "B2", category: "인용/전언" },
  { id: "b2-14-15", form: "V-ㄴ/는다는 것은 N에서/N(으)로 알 수 있다", level: "B2", category: "인용/전언" },
  { id: "b2-15-1", form: "-았/었더라면", level: "B2", category: "조건/가정" },
  { id: "b2-15-2", form: "-거든", level: "B2", category: "조건/가정" },
  { id: "b2-15-3", form: "N(이)면 N, N(이)면 N", level: "B2", category: "조건/가정" },
  { id: "b2-16-1", form: "A-(으)ㄴ지 A-(으)ㄴ지", level: "B2", category: "반복/나열 구문" },
  { id: "b2-16-2", form: "A/V-든(지) A/V-든(지)", level: "B2", category: "반복/나열 구문" },
  { id: "b2-16-3", form: "N(이)든(지) N(이)든(지)", level: "B2", category: "반복/나열 구문" },
  { id: "b2-16-4", form: "N(이)며 N(이)며", level: "B2", category: "반복/나열 구문" },
  { id: "b2-16-5", form: "V-는지 V-는지", level: "B2", category: "반복/나열 구문" },
  { id: "b2-17-1", form: "-기 마련이다", level: "B2", category: "정도/강조" },
  { id: "b2-17-2", form: "-기(가) 무섭게", level: "B2", category: "정도/강조" },
  { id: "b2-17-3", form: "-기는(요)", level: "B2", category: "정도/강조" },
  { id: "b2-17-4", form: "-기는커녕", level: "B2", category: "정도/강조" },
  { id: "b2-17-5", form: "-느니 차라리", level: "B2", category: "정도/강조" },
  { id: "b2-17-6", form: "만에", level: "B2", category: "정도/강조" },
  { id: "b2-17-7", form: "뿐만 아니라", level: "B2", category: "정도/강조" },
  { id: "b2-17-8", form: "설마 A/V-겠어요?", level: "B2", category: "정도/강조" },
  { id: "b2-17-9", form: "어찌나[얼마나] A-(으)ㄴ지", level: "B2", category: "정도/강조" },
  { id: "b2-17-10", form: "어찌나[얼마나] V-는지", level: "B2", category: "정도/강조" },
  { id: "b2-17-11", form: "에 불과하다", level: "B2", category: "정도/강조" },
  { id: "b2-17-12", form: "여간 A-(으)ㄴ 것이 아니다", level: "B2", category: "정도/강조" },
  { id: "b2-17-13", form: "여간 A/V지 않다", level: "B2", category: "정도/강조" },
  { id: "b2-17-14", form: "여간 V-는 것이 아니다", level: "B2", category: "정도/강조" },
  { id: "b2-18-1", form: "-(으)ㄴ 데다가", level: "B2", category: "기타" },
  { id: "b2-18-2", form: "-(으)ㄴ 반면(에)", level: "B2", category: "기타" },
  { id: "b2-18-3", form: "-(으)ㄴ가?", level: "B2", category: "기타" },
  { id: "b2-18-4", form: "-(으)ㄹ 게 아니라", level: "B2", category: "기타" },
  { id: "b2-18-5", form: "-(으)ㄹ 수밖에 없다", level: "B2", category: "기타" },
  { id: "b2-18-6", form: "-(으)ㄹ 정도이다", level: "B2", category: "기타" },
  { id: "b2-18-7", form: "-(으)ㅁ", level: "B2", category: "기타" },
  { id: "b2-18-8", form: "-(으)며", level: "B2", category: "기타" },
  { id: "b2-18-9", form: "-고 해서", level: "B2", category: "기타" },
  { id: "b2-18-10", form: "-는 데다가", level: "B2", category: "기타" },
  { id: "b2-18-11", form: "-는가?", level: "B2", category: "기타" },
  { id: "b2-18-12", form: "-아/어 대다", level: "B2", category: "기타" },
  { id: "b2-18-13", form: "-아/어다(가)", level: "B2", category: "기타" },
  { id: "b2-18-14", form: "-았/었었-", level: "B2", category: "기타" },
  { id: "b2-18-15", form: "(으)로부터", level: "B2", category: "기타" },
  { id: "b2-18-16", form: "(으)로서", level: "B2", category: "기타" },
  { id: "b2-18-17", form: "과/와 달리", level: "B2", category: "기타" },
  { id: "b2-18-18", form: "치고", level: "B2", category: "기타" },
  { id: "b2-18-19", form: "에 비해(서)", level: "B2", category: "기타" },
  { id: "c1-1-1", form: "-던", level: "C1", category: "고급 문법" },
  { id: "c1-1-2", form: "-(으)ㄴ 바 있다", level: "C1", category: "고급 문법" },
  { id: "c1-1-3", form: "-(으)로 인해", level: "C1", category: "고급 문법" },
  { id: "c1-2-1", form: "-ㅂ니다/습니다", level: "C1", category: "격식체" },
  { id: "c1-2-2", form: "-는바", level: "C1", category: "격식체" },
  { id: "c1-2-3", form: "-고자", level: "C1", category: "격식체" },
  { id: "c1-3-1", form: "-다고 하다", level: "C1", category: "인용" },
  { id: "c1-3-2", form: "-(으)라고 하다", level: "C1", category: "인용" },
  { id: "c1-3-3", form: "-냐고 하다", level: "C1", category: "인용" },
  { id: "c1-3-4", form: "-자고 하다", level: "C1", category: "인용" },
  { id: "c1-4-1", form: "-더니", level: "C1", category: "회상" },
  { id: "c1-4-2", form: "-더라", level: "C1", category: "회상" },
  { id: "c1-4-3", form: "-던", level: "C1", category: "회상" },
  { id: "c1-4-4", form: "-던가요", level: "C1", category: "회상" },
  { id: "c1-5-1", form: "조차", level: "C1", category: "강조" },
  { id: "c1-6-1", form: "-다거나", level: "C1", category: "나열/선택" },
  { id: "c1-6-2", form: "-든지", level: "C1", category: "나열/선택" },
  { id: "c1-7-1", form: "-듯이", level: "C1", category: "비유" },
  { id: "c1-7-2", form: "-다시피", level: "C1", category: "비유" },
  { id: "c1-8-1", form: "-(으)ㄴ/는 만큼", level: "C1", category: "정도/속성" },
  { id: "c1-8-2", form: "-(으)ㄴ/는 법이다", level: "C1", category: "정도/속성" },
  { id: "c1-9-1", form: "-(이)나 -(이)나 할 것 없이", level: "C1", category: "한정" },
  { id: "c1-10-1", form: "-을/를 통해(서)", level: "C1", category: "기타" },
  { id: "c1-10-2", form: "-에 관해(서)", level: "C1", category: "기타" },
  { id: "c1-10-3", form: "-(으)ㄴ/는들", level: "C1", category: "기타" },
  { id: "c1-10-4", form: "-기 십상이다", level: "C1", category: "기타" },
  { id: "c1-11-1", form: "-(으)ㄴ", level: "C1", category: "관형사형" },
  { id: "c1-11-2", form: "-는", level: "C1", category: "관형사형" },
  { id: "c1-11-3", form: "-(으)ㄹ", level: "C1", category: "관형사형" },
  { id: "c1-1-4", form: "-(으)ㄴ 나머지", level: "C1", category: "고급 문법" },
  { id: "c1-1-5", form: "-(으)ㄴ 후에야 (비로소)", level: "C1", category: "고급 문법" },
  { id: "c1-1-6", form: "-(으)ㄴ들", level: "C1", category: "고급 문법" },
  { id: "c1-1-7", form: "-(으)려는지", level: "C1", category: "고급 문법" },
  { id: "c1-1-8", form: "-(으)련만", level: "C1", category: "고급 문법" },
  { id: "c1-1-9", form: "-(으)ㅁ에 따라", level: "C1", category: "고급 문법" },
  { id: "c1-1-10", form: "-(으)ㅁ에 틀림없다", level: "C1", category: "고급 문법" },
  { id: "c1-1-11", form: "-(으)ㅁ으로써", level: "C1", category: "고급 문법" },
  { id: "c1-1-12", form: "-겠거니", level: "C1", category: "고급 문법" },
  { id: "c1-1-13", form: "-기에", level: "C1", category: "고급 문법" },
  { id: "c1-1-14", form: "-노라면", level: "C1", category: "고급 문법" },
  { id: "c1-1-15", form: "-는 한이 있어도", level: "C1", category: "고급 문법" },
  { id: "c1-1-16", form: "-되", level: "C1", category: "고급 문법" },
  { id: "c1-1-17", form: "-았/었으면 하다", level: "C1", category: "고급 문법" },
  { id: "c1-1-18", form: "-지 않을까 하다", level: "C1", category: "고급 문법" },
  { id: "c1-1-19", form: "을/를 계기로", level: "C1", category: "고급 문법" },
  { id: "c1-1-20", form: "을/를 바탕으로", level: "C1", category: "고급 문법" },
  { id: "c1-1-21", form: "인지/일까", level: "C1", category: "고급 문법" },
  { id: "c1-1-22", form: "A-(으)ㄴ/V-는 탓", level: "C1", category: "고급 문법" },
  { id: "c1-2-4", form: "-(으)오니", level: "C1", category: "격식체" },
  { id: "c1-3-5", form: "-다는 거야", level: "C1", category: "인용" },
  { id: "c1-3-6", form: "-다는 소리를 듣다", level: "C1", category: "인용" },
  { id: "c1-3-7", form: "-다는 인상을 주다", level: "C1", category: "인용" },
  { id: "c1-3-8", form: "-다는 점을 인정하다", level: "C1", category: "인용" },
  { id: "c1-3-9", form: "-다는 지적이 있다", level: "C1", category: "인용" },
  { id: "c1-4-5", form: "그러더라고(요)", level: "C1", category: "회상" },
  { id: "c1-5-2", form: "-다고 해도 과언이 아니다", level: "C1", category: "강조" },
  { id: "c1-5-3", form: "뭐니 뭐니 해도", level: "C1", category: "강조" },
  { id: "c1-5-4", form: "은/는 물론이거니와", level: "C1", category: "강조" },
  { id: "c1-5-5", form: "은/는 물론이려니와", level: "C1", category: "강조" },
  { id: "c1-6-3", form: "-거나 하다", level: "C1", category: "나열/선택" },
  { id: "c1-6-4", form: "(V-(으)ㄹ 겸) V-(으)ㄹ 겸 (해서)", level: "C1", category: "나열/선택" },
  { id: "c1-6-5", form: "A-(으)ㄴ/V-는데(에) 반해", level: "C1", category: "나열/선택" },
  { id: "c1-6-6", form: "A-(으)ㄴ/V-는데(에) 비해", level: "C1", category: "나열/선택" },
  { id: "c1-6-7", form: "A-(으)ㄴ가/V-는가 하면", level: "C1", category: "나열/선택" },
  { id: "c1-6-8", form: "N 및 N", level: "C1", category: "나열/선택" },
  { id: "c1-6-9", form: "N(이)니 N(이)니 하다", level: "C1", category: "나열/선택" },
  { id: "c1-6-10", form: "N이자 N", level: "C1", category: "나열/선택" },
  { id: "c1-7-3", form: "-다시피 하다", level: "C1", category: "비유" },
  { id: "c1-8-3", form: "-(으)ㄹ 법하다", level: "C1", category: "정도/속성" },
  { id: "c1-8-4", form: "-(으)ㄹ 지경이다", level: "C1", category: "정도/속성" },
  { id: "c1-8-5", form: "-(으)리만큼", level: "C1", category: "정도/속성" },
  { id: "c1-8-6", form: "-기 그지없다", level: "C1", category: "정도/속성" },
  { id: "c1-8-7", form: "-기 나름이다", level: "C1", category: "정도/속성" },
  { id: "c1-8-8", form: "-기 짝이 없다", level: "C1", category: "정도/속성" },
  { id: "c1-8-9", form: "A-(으)ㄴ/V-는 면이 있다", level: "C1", category: "정도/속성" },
  { id: "c1-8-10", form: "A-(으)ㄴ/V-는 점이 특징적이다", level: "C1", category: "정도/속성" },
  { id: "c1-9-2", form: "(이)나마", level: "C1", category: "한정" },
  { id: "c1-9-3", form: "(이)라고는", level: "C1", category: "한정" },
  { id: "c1-9-4", form: "너나없이 (모두)", level: "C1", category: "한정" },
  { id: "c1-9-5", form: "단", level: "C1", category: "한정" },
  { id: "c1-9-6", form: "에 한하여", level: "C1", category: "한정" },
  { id: "c1-9-7", form: "외", level: "C1", category: "한정" },
  { id: "c1-9-8", form: "을/를 막론하고", level: "C1", category: "한정" },
  { id: "c1-9-9", form: "N(이)란 N은/는 모두", level: "C1", category: "한정" },
  { id: "c1-10-5", form: "-(으)ㄹ뿐더러", level: "C1", category: "기타" },
  { id: "c1-10-6", form: "-(으)면 그만이다", level: "C1", category: "기타" },
  { id: "c1-10-7", form: "-는 둥 마는 둥", level: "C1", category: "기타" },
  { id: "c1-10-8", form: "-아/어 내다", level: "C1", category: "기타" },
  { id: "c1-10-9", form: "-지(요), 뭐", level: "C1", category: "기타" },
  { id: "c1-10-10", form: "길이", level: "C1", category: "기타" },
  { id: "c1-10-11", form: "바람이 불다", level: "C1", category: "기타" },
  { id: "c1-10-12", form: "생각다 못해", level: "C1", category: "기타" },
  { id: "c1-10-13", form: "여부", level: "C1", category: "기타" },
  { id: "c1-10-14", form: "이/가 눈길을 끌다", level: "C1", category: "기타" },
  { id: "c1-10-15", form: "이래 가지고(서)(야)", level: "C1", category: "기타" },
  { id: "c1-10-16", form: "A-(으)ㄴ/V-는) N에 (A-(으)ㄴ/는) N", level: "C1", category: "기타" },
  { id: "c1-10-17", form: "N(까지)는 못 돼도 N은/는 A/V-(으)ㄹ 줄 알았다", level: "C1", category: "기타" },
  { id: "c1-10-18", form: "V-는 등 (N에) 재능을 발휘하다", level: "C1", category: "기타" },
  { id: "c1-12-1", form: "-는 경향을 보이다", level: "C1", category: "학술/담화표지" },
  { id: "c1-12-2", form: "-는 추세이다", level: "C1", category: "학술/담화표지" },
  { id: "c1-12-3", form: "다시 말해서", level: "C1", category: "학술/담화표지" },
  { id: "c1-12-4", form: "따지고 보면", level: "C1", category: "학술/담화표지" },
  { id: "c1-12-5", form: "아래와 같이", level: "C1", category: "학술/담화표지" },
  { id: "c1-12-6", form: "에 대한 논란이 있다", level: "C1", category: "학술/담화표지" },
  { id: "c1-12-7", form: "을/를 말하라면", level: "C1", category: "학술/담화표지" },
  { id: "c1-12-8", form: "이/가 중요한 역할을 하다", level: "C1", category: "학술/담화표지" },
  { id: "c1-12-9", form: "이상에서 본 바와 같이", level: "C1", category: "학술/담화표지" },
  { id: "c1-12-10", form: "한마디로 말하자면", level: "C1", category: "학술/담화표지" },
  { id: "c1-12-11", form: "한편으로(는)", level: "C1", category: "학술/담화표지" },
  { id: "c1-12-12", form: "A/V-다는 응답이 N에 달하다", level: "C1", category: "학술/담화표지" },
  { id: "c1-12-13", form: "N에서 N의 비중이 높다", level: "C1", category: "학술/담화표지" },
  { id: "c1-12-14", form: "N은/는 A/V-(으)ㅁ을 말해 주다", level: "C1", category: "학술/담화표지" },
  { id: "c1-12-15", form: "N은/는 N에 그치다", level: "C1", category: "학술/담화표지" },
  { id: "c1-12-16", form: "N은/는 N을/를 보여 주는 좋은 예이다", level: "C1", category: "학술/담화표지" },
  { id: "c1-12-17", form: "N을/를 시작으로 N을/를 거쳐 N을/를 맡다", level: "C1", category: "학술/담화표지" },
  { id: "c1-12-18", form: "N을/를 N(으)로 꼽다", level: "C1", category: "학술/담화표지" },
  { id: "c1-12-19", form: "N의 대표적인 예로 N을/를 들다", level: "C1", category: "학술/담화표지" },
  { id: "c1-12-20", form: "N의 특징은 A/V-다는데(에) 있다", level: "C1", category: "학술/담화표지" },
  { id: "c2-1-1", form: "-(으)ㄹ지라도", level: "C2", category: "양보/한정" },
  { id: "c2-1-2", form: "-(으)ㄴ/는 한", level: "C2", category: "양보/한정" },
];

// 문법 목록이 아닌 줄(제목·규칙·어휘·길이 등)과, 문법 줄이 원래 있던 위치를 그대로 담는다.
type TemplateEntry = { type: "literal"; text: string } | { type: "grammar"; catIndex: number; prefix: string; category: string };

const LEVEL_TEMPLATE: Record<CefrLevel, TemplateEntry[]> = {
  A1: [
    { type: "literal", text: "" },
    { type: "literal", text: "   **A1 (TOPIK I 초급 1급)**: " },
    { type: "grammar", catIndex: 1, prefix: "   ", category: "서술/종결" },
    { type: "grammar", catIndex: 2, prefix: "   ", category: "지시/장소" },
    { type: "grammar", catIndex: 3, prefix: "   ", category: "조사" },
    { type: "grammar", catIndex: 4, prefix: "   ", category: "부정" },
    { type: "grammar", catIndex: 5, prefix: "   ", category: "존재" },
    { type: "grammar", catIndex: 6, prefix: "   ", category: "희망" },
    { type: "grammar", catIndex: 7, prefix: "   ", category: "계획/미래" },
    { type: "grammar", catIndex: 8, prefix: "   ", category: "목적" },
    { type: "grammar", catIndex: 9, prefix: "   ", category: "능력/숙련도" },
    { type: "grammar", catIndex: 10, prefix: "   ", category: "의무" },
    { type: "grammar", catIndex: 11, prefix: "   ", category: "이유" },
    { type: "grammar", catIndex: 12, prefix: "   ", category: "조건" },
    { type: "grammar", catIndex: 13, prefix: "   ", category: "대조/나열" },
    { type: "grammar", catIndex: 14, prefix: "   ", category: "시간" },
    { type: "grammar", catIndex: 15, prefix: "   ", category: "진행" },
    { type: "grammar", catIndex: 16, prefix: "   ", category: "높임" },
    { type: "grammar", catIndex: 17, prefix: "   ", category: "요청/권유" },
    { type: "grammar", catIndex: 18, prefix: "   ", category: "도움" },
    { type: "grammar", catIndex: 19, prefix: "   ", category: "시도/권유" },
    { type: "grammar", catIndex: 20, prefix: "   ", category: "수식" },
    { type: "grammar", catIndex: 21, prefix: "   ", category: "단위" },
    { type: "literal", text: "   - 길이: 4-6어절(띄어쓰기로 나눈 덩어리 수)" },
  ],
  A2: [
    { type: "literal", text: "" },
    { type: "literal", text: "   **A2 (TOPIK I 초중급 2급) - 핵심 문법 필수 사용**:" },
    { type: "literal", text: "   **규칙: 문제마다 아래 나열된 A2 문법 표현 중 하나를 반드시 포함하세요.**" },
    { type: "literal", text: "   " },
    { type: "grammar", catIndex: 1, prefix: "   ", category: "서술/종결" },
    { type: "grammar", catIndex: 2, prefix: "   ", category: "의문(부드러움)" },
    { type: "grammar", catIndex: 3, prefix: "   ", category: "부정" },
    { type: "grammar", catIndex: 4, prefix: "   ", category: "이유(심화)" },
    { type: "grammar", catIndex: 5, prefix: "   ", category: "순서(연속 동작)" },
    { type: "grammar", catIndex: 6, prefix: "   ", category: "동시동작/시간" },
    { type: "grammar", catIndex: 7, prefix: "   ", category: "배경/대조" },
    { type: "grammar", catIndex: 8, prefix: "   ", category: "추측" },
    { type: "grammar", catIndex: 9, prefix: "   ", category: "양태/외견" },
    { type: "grammar", catIndex: 10, prefix: "   ", category: "제안/의지/권유" },
    { type: "grammar", catIndex: 11, prefix: "   ", category: "계획/의도" },
    { type: "grammar", catIndex: 12, prefix: "   ", category: "결심/약속/계획" },
    { type: "grammar", catIndex: 13, prefix: "   ", category: "희망" },
    { type: "grammar", catIndex: 14, prefix: "   ", category: "허락/금지" },
    { type: "grammar", catIndex: 15, prefix: "   ", category: "양보" },
    { type: "grammar", catIndex: 16, prefix: "   ", category: "변화" },
    { type: "grammar", catIndex: 17, prefix: "   ", category: "경험/시도" },
    { type: "grammar", catIndex: 18, prefix: "   ", category: "능력/숙련도" },
    { type: "grammar", catIndex: 19, prefix: "   ", category: "평가" },
    { type: "grammar", catIndex: 20, prefix: "   ", category: "조건/방법" },
    { type: "grammar", catIndex: 21, prefix: "   ", category: "상태/성향" },
    { type: "grammar", catIndex: 22, prefix: "   ", category: "보조용언" },
    { type: "grammar", catIndex: 23, prefix: "   ", category: "나열/선택" },
    { type: "grammar", catIndex: 24, prefix: "   ", category: "조사" },
    { type: "grammar", catIndex: 25, prefix: "   ", category: "비교" },
    { type: "grammar", catIndex: 26, prefix: "   ", category: "부사형" },
    { type: "grammar", catIndex: 27, prefix: "   ", category: "인용(명사)" },
    { type: "grammar", catIndex: 28, prefix: "   ", category: "명사화" },
    { type: "grammar", catIndex: 29, prefix: "   ", category: "관형사형" },
    { type: "grammar", catIndex: 30, prefix: "   ", category: "지식/인지" },
    { type: "literal", text: "   - 길이: 5-9어절(띄어쓰기로 나눈 덩어리 수)" },
  ],
  B1: [
    { type: "literal", text: "" },
    { type: "literal", text: "   **B1 (TOPIK II 중급 3급) - 핵심 문법 필수 사용**:" },
    { type: "literal", text: "   **규칙: 문제마다 아래 나열된 B1 문법 표현 중 하나를 반드시 포함하세요. 중급 수준의 연결어미와 표현을 사용해주세요.**" },
    { type: "literal", text: "" },
    { type: "literal", text: "   - 어휘: 계획, 경험, 의견, 문제, 환경, 건강, 발전하다, 변화하다, 증가하다, 중요하다" },
    { type: "grammar", catIndex: 1, prefix: "   ", category: "연결어미" },
    { type: "grammar", catIndex: 2, prefix: "   ", category: "간접화법" },
    { type: "grammar", catIndex: 3, prefix: "   ", category: "추측/판단" },
    { type: "grammar", catIndex: 4, prefix: "   ", category: "목적/이유" },
    { type: "grammar", catIndex: 5, prefix: "   ", category: "정도/비교" },
    { type: "grammar", catIndex: 6, prefix: "   ", category: "양보" },
    { type: "grammar", catIndex: 7, prefix: "   ", category: "나열" },
    { type: "grammar", catIndex: 8, prefix: "   ", category: "피동/사동" },
    { type: "grammar", catIndex: 9, prefix: "   ", category: "후회/망설임" },
    { type: "grammar", catIndex: 10, prefix: "   ", category: "회상/배경" },
    { type: "grammar", catIndex: 11, prefix: "   ", category: "가장/화제" },
    { type: "grammar", catIndex: 12, prefix: "   ", category: "기타" },
    { type: "grammar", catIndex: 13, prefix: "   ", category: "관형사형" },
    { type: "grammar", catIndex: 14, prefix: "   ", category: "서술/종결" },
    { type: "grammar", catIndex: 15, prefix: "   ", category: "완료/회상" },
    { type: "grammar", catIndex: 16, prefix: "   ", category: "계획/의도" },
    { type: "grammar", catIndex: 17, prefix: "   ", category: "조건/가정" },
    { type: "grammar", catIndex: 18, prefix: "   ", category: "구어체 종결" },
    { type: "literal", text: "   - 길이: 8-11어절(띄어쓰기로 나눈 덩어리 수)" },
  ],
  B2: [
    { type: "literal", text: "" },
    { type: "literal", text: "   **B2 (TOPIK II 중고급 4급) - 핵심 문법 필수 사용**:" },
    { type: "literal", text: "   **규칙: 문제마다 아래 나열된 B2 문법 표현 중 하나를 반드시 포함하세요. 고급 연결어미와 피동/사동 표현을 적극적으로 사용해주세요.**" },
    { type: "literal", text: "" },
    { type: "literal", text: "   - 어휘: 상황, 현상, 영향, 결과, 원인, 심각하다, 복잡하다, 다양하다, 강조하다" },
    { type: "grammar", catIndex: 1, prefix: "   ", category: "고급 연결" },
    { type: "grammar", catIndex: 2, prefix: "   ", category: "피동/사동" },
    { type: "grammar", catIndex: 3, prefix: "   ", category: "추측/양태" },
    { type: "grammar", catIndex: 4, prefix: "   ", category: "목적" },
    { type: "grammar", catIndex: 5, prefix: "   ", category: "정도" },
    { type: "grammar", catIndex: 6, prefix: "   ", category: "이유/근거" },
    { type: "grammar", catIndex: 7, prefix: "   ", category: "양보" },
    { type: "grammar", catIndex: 8, prefix: "   ", category: "강조/극단" },
    { type: "grammar", catIndex: 9, prefix: "   ", category: "회상/전달" },
    { type: "grammar", catIndex: 10, prefix: "   ", category: "열거" },
    { type: "grammar", catIndex: 11, prefix: "   ", category: "의도" },
    { type: "grammar", catIndex: 12, prefix: "   ", category: "기타" },
    { type: "grammar", catIndex: 13, prefix: "   ", category: "관형사형" },
    { type: "grammar", catIndex: 14, prefix: "   ", category: "인용/전언" },
    { type: "grammar", catIndex: 15, prefix: "   ", category: "조건/가정" },
    { type: "grammar", catIndex: 16, prefix: "   ", category: "반복/나열 구문" },
    { type: "grammar", catIndex: 17, prefix: "   ", category: "정도/강조" },
    { type: "grammar", catIndex: 18, prefix: "   ", category: "기타" },
    { type: "literal", text: "   - 길이: 10-15어절(띄어쓰기로 나눈 덩어리 수)" },
  ],
  C1: [
    { type: "literal", text: "" },
    { type: "literal", text: "   **C1 (TOPIK II 고급 5급 이상) - 핵심 문법 필수 사용**:" },
    { type: "literal", text: "   **규칙: 문제마다 아래 나열된 C1 문법 표현 중 하나를 반드시 포함하세요. 격식체와 문어체 표현을 사용하여 고급스러운 문장을 만들어주세요.**" },
    { type: "literal", text: "" },
    { type: "literal", text: "   - 어휘: 지속, 체계, 필수, 도출, 분석, 기여하다, 촉진하다, 저해하다, 효율적, 합리적" },
    { type: "grammar", catIndex: 1, prefix: "   ", category: "고급 문법" },
    { type: "grammar", catIndex: 2, prefix: "   ", category: "격식체" },
    { type: "grammar", catIndex: 3, prefix: "   ", category: "인용" },
    { type: "grammar", catIndex: 4, prefix: "   ", category: "회상" },
    { type: "grammar", catIndex: 5, prefix: "   ", category: "강조" },
    { type: "grammar", catIndex: 6, prefix: "   ", category: "나열/선택" },
    { type: "grammar", catIndex: 7, prefix: "   ", category: "비유" },
    { type: "grammar", catIndex: 8, prefix: "   ", category: "정도/속성" },
    { type: "grammar", catIndex: 9, prefix: "   ", category: "한정" },
    { type: "grammar", catIndex: 10, prefix: "   ", category: "기타" },
    { type: "grammar", catIndex: 11, prefix: "   ", category: "관형사형" },
    { type: "grammar", catIndex: 12, prefix: "   ", category: "학술/담화표지" },
    { type: "literal", text: "   - 길이: 12-17어절(띄어쓰기로 나눈 덩어리 수)" },
  ],
  C2: [
    { type: "literal", text: "" },
    { type: "literal", text: "   **C2 (최고급) - 핵심 문법 필수 사용**:" },
    { type: "literal", text: "   **규칙: 가능한 한 복잡하고 정교한 문장 구조를 사용하세요. 학술적이거나 전문적인 맥락의 어휘와 표현을 적극 사용해주세요.**" },
    { type: "literal", text: "" },
    { type: "literal", text: "   - 사용 가능: 학술 용어, 전문 어휘, 관용 표현" },
    { type: "grammar", catIndex: 1, prefix: "   ", category: "양보/한정" },
    { type: "literal", text: "   - 문법: 매우 복잡한 구조, 격식체" },
    { type: "literal", text: "   - 길이: 13-18어절(띄어쓰기로 나눈 덩어리 수)" },
  ],
};

/** DIFFICULTY_GUIDES[level]과 동일한 문자열을 GRAMMAR_ITEMS로부터 만든다. */
export function renderGuide(level: CefrLevel): string {
  const itemsByCat = new Map<number, string[]>();
  for (const it of GRAMMAR_ITEMS) {
    if (it.level !== level) continue;
    const catIndex = Number(it.id.split("-")[1]);
    const list = itemsByCat.get(catIndex) ?? [];
    list.push(it.form);
    itemsByCat.set(catIndex, list);
  }
  return LEVEL_TEMPLATE[level]
    .map((entry) =>
      entry.type === "literal"
        ? entry.text
        : `${entry.prefix}- ${entry.category}: ${(itemsByCat.get(entry.catIndex) ?? []).join(", ")}`
    )
    .join("\n");
}
